### ISSUE TITLE
[htmap.launch] is neither a launch file in package [htmap] nor is [htmap] a launch file name

### ISSUE THREAD

**Issue by weidom** [emiliofidalgo/htmap#5]
I followed the instructions and successfully compiled this project，but when I run it got this error message:
 
```
xx@ubuntu:~/work_space/src/htmap/launch$ roslaunch htmap htmap.launch image_dir:="/image/dir" working_dir:="~/Desktop/htmap"
[htmap.launch] is neither a launch file in package [htmap] nor is [htmap] a launch file name
The traceback for the exception was written to the log file
```

Please tell me what should I do?

**Comment by emiliofidalgo** [comment]
It seems a problem with your ROS configuration. If you just downloaded the package and compile it, you need to source again your .bashrc configuration to find the package in your ROS path. Try this:

`rospack profile`

Otherwise, close your current terminal and open it again. More info:

https://answers.ros.org/question/143496/roslaunch-is-neither-a-launch-file-in-package-nor-is-a-launch-file-name/
